# Generated by ariadne-codegen
# Source: queries.gql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import AccountHolderApplicationStatusCode


class CreateAccountHolderCardProductApplication(BaseModel):
    create_account_holder_card_product_application: Optional[
        Annotated[
            Union[
                "CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccountHolderCardProductApplication",
                "CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationUserError",
                "CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccessDeniedError",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="createAccountHolderCardProductApplication")


class CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccountHolderCardProductApplication(
    BaseModel
):
    typename__: Literal["AccountHolderCardProductApplication"] = Field(
        alias="__typename"
    )
    id: str
    application_state: Optional[
        "CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccountHolderCardProductApplicationApplicationState"
    ] = Field(alias="applicationState")
    updated_at: Optional[str] = Field(alias="updatedAt")
    created_at: Optional[str] = Field(alias="createdAt")


class CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccountHolderCardProductApplicationApplicationState(
    BaseModel
):
    status: AccountHolderApplicationStatusCode


class CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationUserError(
    BaseModel
):
    typename__: Literal["UserError"] = Field(alias="__typename")
    errors: Optional[
        List[
            "CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationUserErrorErrors"
        ]
    ]


class CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationUserErrorErrors(
    BaseModel
):
    path: Optional[List[str]]
    code: Optional[str]
    description: Optional[str]


class CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccessDeniedError(
    BaseModel
):
    typename__: Literal["AccessDeniedError"] = Field(alias="__typename")


CreateAccountHolderCardProductApplication.model_rebuild()
CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationAccountHolderCardProductApplication.model_rebuild()
CreateAccountHolderCardProductApplicationCreateAccountHolderCardProductApplicationUserError.model_rebuild()
