# Generated by ariadne-codegen
# Source: queries.gql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import PaymentCardNetwork, PaymentCardStatus


class IssuePaymentCardForFinancialAccount(BaseModel):
    issue_payment_card_for_financial_account: Optional[
        Annotated[
            Union[
                "IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountPaymentCard",
                "IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountUserError",
                "IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountAccessDeniedError",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="issuePaymentCardForFinancialAccount")


class IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountPaymentCard(
    BaseModel
):
    typename__: Literal["PaymentCard"] = Field(alias="__typename")
    id: str
    bin: Optional[str]
    last_4: Optional[str] = Field(alias="last4")
    expiration_date: Optional[str] = Field(alias="expirationDate")
    network: Optional[PaymentCardNetwork]
    status: Optional[PaymentCardStatus]


class IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountUserError(
    BaseModel
):
    typename__: Literal["UserError"] = Field(alias="__typename")
    errors: Optional[
        List[
            "IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountUserErrorErrors"
        ]
    ]


class IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountUserErrorErrors(
    BaseModel
):
    path: Optional[List[str]]
    code: Optional[str]
    description: Optional[str]


class IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountAccessDeniedError(
    BaseModel
):
    typename__: Literal["AccessDeniedError"] = Field(alias="__typename")


IssuePaymentCardForFinancialAccount.model_rebuild()
IssuePaymentCardForFinancialAccountIssuePaymentCardForFinancialAccountUserError.model_rebuild()
