# Generated by ariadne-codegen
# Source: queries.gql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AccountHolderApplicationStatusCode,
    AccountHolderVerificationResultCode,
    AccountHolderVerificationStatusCode,
    AccountHolderVerificationStatusReasonCode,
)


class LookupApplication(BaseModel):
    node: Optional[
        Annotated[
            Union[
                "LookupApplicationNodeNode",
                "LookupApplicationNodeAccountHolderCardProductApplication",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class LookupApplicationNodeNode(BaseModel):
    typename__: Literal[
        "APIKey",
        "AccountHolderApplicationDocument",
        "AccountHolderCardProductApplicationOffer",
        "AccountHolderProvisioning",
        "AccountHolderProvisioningWorkflowAction",
        "AccountStatusActiveEvent",
        "AccountStatusClosedEvent",
        "AccountStatusPendingClosureEvent",
        "AccountStatusSuspendedEvent",
        "AccountStatusUnderReviewEvent",
        "AchExternallyInitatedDepositFailedEvent",
        "AchExternallyInitatedDepositProcessedEvent",
        "AchExternallyInitatedDepositReceivedEvent",
        "AchExternallyInitiatedWithdrawalFailedEvent",
        "AchExternallyInitiatedWithdrawalProcessedEvent",
        "AchExternallyInitiatedWithdrawalReceivedEvent",
        "AchHoldAddedEvent",
        "AchHoldRemovedEvent",
        "AchTransferHoldAddedEvent",
        "AchTransferHoldRemovedEvent",
        "AdminAgentOrganization",
        "AmountLimitInterFinancialAccountTransferRule",
        "AmountLimitSpendRule",
        "AuthorizationAndClearEvent",
        "AuthorizationEvent",
        "AuthorizedUserCardProductApplication",
        "BalanceInquiryEvent",
        "CVVSpendRule",
        "CardArtDocument",
        "CardDataInputCapabilitySpendRule",
        "CardDigitalWalletToken",
        "CardDigitalWalletTokenActivatedEvent",
        "CardDigitalWalletTokenSuspendedEvent",
        "CardDigitalWalletTokenTerminatedEvent",
        "CardProduct",
        "CardProfileDocumentUploadSession",
        "CardProfileSet",
        "CardProfileSetRestricted",
        "CardTransactionProcessingTypeConditionSpendRule",
        "ClearingEvent",
        "CollaborativeAuthorizationEndpoint",
        "CommercialChargeCardFinancialAccountStatement",
        "CommercialRevolvingCardFinancialAccountStatement",
        "ConditionalRuleSetSpendRule",
        "ConsumerChargeCardFinancialAccountStatement",
        "ConsumerRevolvingCardFinancialAccountStatement",
        "CountLimitInterFinancialAccountTransferRule",
        "CountLimitSpendRule",
        "CreditCardTransferEvent",
        "CreditFunds",
        "CreditFundsACHTransferEvent",
        "CreditLedgerEntry",
        "CreditLimitChangeRequest",
        "CreditPayInFullCardFinancialAccountStatement",
        "CreditPlan",
        "CreditPlanTemplate",
        "CreditTransaction",
        "DebitFunds",
        "DebitFundsACHTransferEvent",
        "DebitLedgerEntry",
        "DebitTransaction",
        "DeliveryAttempt",
        "DepositAmountLimitSpendRule",
        "DepositCountLimitSpendRule",
        "DepositProcessingNetworkSpendRule",
        "DigitalCardProfile",
        "DirectDepositDetail",
        "DisbursementTransferEvent",
        "DocumentUploadLink",
        "EmployerFinancialAccount",
        "EnhancedDataEvent",
        "ExternalBankAccountAddedEvent",
        "ExternalBankAccountDetail",
        "ExternalBankAccountRemovedEvent",
        "ExternalFinancialBankAccount",
        "ExternallyInitiatedAchReleaseHoldTransfer",
        "ExternallyInitiatedWireTransfer",
        "FeeChargeRule",
        "FeeSchedule",
        "FeeTransferEvent",
        "FinancialAccount",
        "FinancialAccountCreditLimitUpdateFromProductFunding",
        "FinancialAccountPseudoBalanceUpdate",
        "FinancialAccountSnapshot",
        "FinancialAccountStatementReadyEvent",
        "FundsDepositCanceledEvent",
        "FundsDepositFailedEvent",
        "FundsDepositInitiatedEvent",
        "FundsDepositProcessedEvent",
        "FundsDepositProcessingEvent",
        "FundsDepositReturnedEvent",
        "FundsWithdrawalCanceledEvent",
        "FundsWithdrawalFailedEvent",
        "FundsWithdrawalInitiatedEvent",
        "FundsWithdrawalProcessedEvent",
        "FundsWithdrawalProcessingEvent",
        "FundsWithdrawalReturnedEvent",
        "IdentityVerificationDocumentUploadSession",
        "IntegratorInitiatedFundsDepositACHTransfer",
        "IntegratorInitiatedFundsDepositACHTransferEvent",
        "IntegratorInitiatedFundsWithdrawalACHTransfer",
        "IntegratorInitiatedFundsWithdrawalACHTransferEvent",
        "InterFinancialAccountTransfer",
        "InternalTransferFromFundingFinancialAccountToPaymentCardFinancialAccountCompletedEvent",
        "InternalTransferFromFundingFinancialAccountToPaymentCardFinancialAccountFailedEvent",
        "InternalTransferFromFundingFinancialAccountToPaymentCardFinancialAccountPendingEvent",
        "InternalTransferFromPaymentCardFinancialAccountToFundingFinancialAccountCompletedEvent",
        "InternalTransferFromPaymentCardFinancialAccountToFundingFinancialAccountFailedEvent",
        "InternalTransferFromPaymentCardFinancialAccountToFundingFinancialAccountPendingEvent",
        "IssuerPreliminaryAuthorizationEvent",
        "JournalEntry",
        "Ledger",
        "ManualAdjustmentEvent",
        "MastercardFleetAuthorizationData",
        "MastercardFleetEnhancedData",
        "MerchantCategorySpendRule",
        "MerchantCountrySpendRule",
        "MerchantIdentifierSpendRule",
        "Node",
        "NonOriginatedAchTransfer",
        "NonOriginatedAchTransferFailedEvent",
        "NonOriginatedAchTransferProcessedEvent",
        "NonOriginatedAchTransferReceivedEvent",
        "NonOriginatedAchTransferReturnedEvent",
        "NonVerifiedExternalUSFinancialBankAccount",
        "NonVerifiedExternalUSFinancialBankAccountDetail",
        "NotificationEvent",
        "OnboardingBusinessOrganizationInformation",
        "OnboardingPreliminaryBusinessInformation",
        "OneTimeACHTransfer",
        "Organization",
        "OriginatedAchTransfer",
        "OriginatedAchTransferCanceledEvent",
        "OriginatedAchTransferFailedEvent",
        "OriginatedAchTransferInitiatedEvent",
        "OriginatedAchTransferPendingEvent",
        "OriginatedAchTransferProcessedEvent",
        "OriginatedAchTransferProcessingEvent",
        "OriginatedAchTransferReturnedEvent",
        "PanEntryModeSpendRule",
        "PaymentCard",
        "PaymentCardActivatedEvent",
        "PaymentCardAuthorizationAndClearApprovedEvent",
        "PaymentCardAuthorizationAndClearDeclinedEvent",
        "PaymentCardAuthorizationApprovedEvent",
        "PaymentCardAuthorizationCreatedEvent",
        "PaymentCardAuthorizationDeclinedEvent",
        "PaymentCardAuthorizationReversedEvent",
        "PaymentCardBinRange",
        "PaymentCardClearedEvent",
        "PaymentCardClosedEvent",
        "PaymentCardEnhancedDataEvent",
        "PaymentCardSnapshot",
        "PaymentCardSuspendedEvent",
        "PaymentCardTransactionChargeback",
        "PaymentCardTransactionDispute",
        "PaymentCardUnsuspendedEvent",
        "PaymentCardVerificationApprovedEvent",
        "PaymentCardVerificationDeclinedEvent",
        "PaymentCreditTransaction",
        "PaymentDebitTransaction",
        "PaymentMethodToken",
        "PaymentOrder",
        "PayrollACHTransferEvent",
        "PayrollAdvance",
        "PayrollAdvanceRepaymentCompletedEvent",
        "PayrollAdvanceRepaymentTransfer",
        "PayrollAdvanceWriteOffCompletedEvent",
        "PayrollAdvanceWriteoffTransfer",
        "PayrollTransfer",
        "PhysicalCardGroupOrder",
        "PhysicalCardProfile",
        "PhysicalPaymentCardGroupOrderShipFailedEvent",
        "PhysicalPaymentCardGroupOrderShippedEvent",
        "PhysicalPaymentCardOrder",
        "PhysicalPaymentCardShipFailedEvent",
        "PhysicalPaymentCardShippedEvent",
        "PointOfServiceCategorySpendRule",
        "PostalCodeVerificationSpendRule",
        "RecurringACHTransfer",
        "RepaymentFailedEvent",
        "RepaymentProcessedEvent",
        "RepaymentProcessingEvent",
        "RepaymentReturnedEvent",
        "Report",
        "RequestedIdentityUpdate",
        "RestrictedAccountHolderSpendRule",
        "ReversalEvent",
        "RewardDefaultEarnRule",
        "RewardMerchantCategoryEarnRule",
        "RewardPointsTransfer",
        "RewardRedemptionConfiguration",
        "RiskApplicationSDK",
        "RiskApplicationSDKRevision",
        "RuleCollection",
        "ScheduledTransferAchEvent",
        "SecureCardBalanceRepaymentACHTransfer",
        "SecureCardBalanceRepaymentACHTransferEvent",
        "SecureDeposit",
        "SecureDepositACHTransfer",
        "SecureDepositACHTransferEvent",
        "SecureDepositCanceledEvent",
        "SecureDepositFailedEvent",
        "SecureDepositInitiatedEvent",
        "SecureDepositProcessedEvent",
        "SecureDepositProcessingEvent",
        "SecureDepositReturnedEvent",
        "SecureDepositTransferEvent",
        "SecuredDepositCommercialCreditCardFinancialAccountStatement",
        "SigningKey",
        "StreetAddressSpendRule",
        "Transfer",
        "TransferPurposeInterFinancialAccountTransferRule",
        "USAccountHolderApplicationDocumentUploadSession",
        "USBusinessAccountHolder",
        "USPersonAccountHolder",
        "USPersonAuthorizedUser",
        "User",
        "ValidatedAddress",
        "VelocityInterFinancialAccountTransferRule",
        "VelocityRule",
        "VerificationEvent",
        "VirtualCardProfile",
        "VisaFleetAuthorizationData",
        "VisaFleetL2TransactionData",
        "VisaFleetL3EnhancedData",
        "WatchlistInterFinancialAccountTransferRule",
        "WebhookNotificationTarget",
        "WireTransfer",
    ] = Field(alias="__typename")


class LookupApplicationNodeAccountHolderCardProductApplication(BaseModel):
    typename__: Literal["AccountHolderCardProductApplication"] = Field(
        alias="__typename"
    )
    typename__: Literal["AccountHolderCardProductApplication"] = Field(
        alias="__typename"
    )
    application_state: Optional[
        "LookupApplicationNodeAccountHolderCardProductApplicationApplicationState"
    ] = Field(alias="applicationState")
    account_holder_snapshot: Optional[
        Annotated[
            Union[
                "LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshot",
                "LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSBusinessAccountHolderSnapshot",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="accountHolderSnapshot")


class LookupApplicationNodeAccountHolderCardProductApplicationApplicationState(
    BaseModel
):
    status: AccountHolderApplicationStatusCode


class LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshot(
    BaseModel
):
    typename__: Literal["USPersonAccountHolderSnapshot"] = Field(alias="__typename")
    current_verification: Optional[
        "LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshotCurrentVerification"
    ] = Field(alias="currentVerification")


class LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshotCurrentVerification(
    BaseModel
):
    status: Optional[AccountHolderVerificationStatusCode]
    reason: Optional[AccountHolderVerificationStatusReasonCode]
    results: Optional[
        List[
            "LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshotCurrentVerificationResults"
        ]
    ]


class LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshotCurrentVerificationResults(
    BaseModel
):
    code: Optional[AccountHolderVerificationResultCode]
    description: Optional[str]


class LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSBusinessAccountHolderSnapshot(
    BaseModel
):
    typename__: Literal["USBusinessAccountHolderSnapshot"] = Field(alias="__typename")


LookupApplication.model_rebuild()
LookupApplicationNodeAccountHolderCardProductApplication.model_rebuild()
LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshot.model_rebuild()
LookupApplicationNodeAccountHolderCardProductApplicationAccountHolderSnapshotUSPersonAccountHolderSnapshotCurrentVerification.model_rebuild()
