# Generated by ariadne-codegen
# Source: queries.gql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ReportType


class ReportUsage(BaseModel):
    report_usage: Optional[List["ReportUsageReportUsage"]] = Field(alias="reportUsage")


class ReportUsageReportUsage(BaseModel):
    report_type: Optional[ReportType] = Field(alias="reportType")
    limit: Optional[Any]
    limit_remaining: Optional[Any] = Field(alias="limitRemaining")
    period_end: Optional[str] = Field(alias="periodEnd")


ReportUsage.model_rebuild()
